"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jogo_1 = require("./modules/jogo");
var personagens_1 = require("./modules/personagens");
var jogo = new jogo_1.Jogo();
var p = new personagens_1.Personagem(1, 'wictor', 200);
var s = new personagens_1.Soldado(2, 'gabriel', 200, 5);
var s2 = new personagens_1.Soldado(3, 'Mourao', 200, 5);
var c = new personagens_1.Cavaleiro(4, 'Crampbell', 200, 8);
jogo.incluir(p);
jogo.incluir(s);
jogo.incluir(s2);
jogo.incluir(c);
jogo.avaliarBatalha();
jogo.atacar(p.id, c.id);
jogo.atacar(s.id, c.id);
jogo.atacar(s2.id, s.id);
jogo.atacar(c.id, s2.id);
jogo.avaliarBatalha();
